version: "3.7"
services:
  mydb:
    image: "mariadb"
    ports:
      - "3906:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
  mytomcat:
    build: .
    depends_on:
      - mydb
    volumes:
      - ./petclinic.war:/usr/local/tomcat/webapps/petclinic.war
    ports:
      - "9090:8080"
  mynginx:
    image: nginx
    depends_on:
      - mytomcat
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
